# 기타 설정을 제외한 나머지는 게임이 진행되고 있는 중에만 적용됩니다. #
# 제시된 조건을 게임 내에 적용하고 싶으시다면, true, 그렇지 않으시다면, false를 입력하시기 바랍니다. #
# true와 false의 철자를 정확히 구분하시기 바랍니다. #
# 난이도를 제외한 나머지는 게임 내 GUI 세팅으로 바꿀 수 있습니다. #

### 게임 관련 설정 ###
인벤토리 클리어: true
스카이블럭 아이템 제공: true
엔티티 제거: true
침대 무시: true

### 월드 관련 설정 ###
서버 자동 저장: true
동물 생성: false
몬스터 생성: false
난이도: 1

### 기타 설정 ###
빠른 시작: true
도박 허용: true
가용 인원 증가: false

#인벤토리 클리어: 게임 시작 시 인벤토리를 클리어합니다.#
#스카이블럭 아이템 제공: 게임 시작 시 스카이블록 아이템을 지급합니다.#
#엔티티 제거: 엔티티(몬스터, 동물)들을 지웁니다.#
#침대 무시: 침대를 무시합니다.#
#서버 자동 저장: 서버 오토세이브를 제어합니다. #
#동물 생성: 동물 스폰을 제어합니다. #
#몬스터 생성: 몬스터 스폰을 제어합니다. #
#난이도: 난이도를 설정합니다. (0: 평화 / 1: 쉬옴 / 2: 보통 / 3:어려움 / 기본값: 쉬움) #
#빠른 시작: /t start 후 4.5초 만에 준비가 끝납니다. #
#도박 허용: /t con을 통한 도박을 허용합니다.#